### ISSUE TITLE
test_scala fails because of python

### ISSUE THREAD

**Issue by plaszczy** [astrolabsoftware/spark3D#118]
test_scala uses a python call to retrieve SCALA_BINARY_VERSION. However
-this requires setting the PYTHONPATH
-it requires having py4j installed 

it woulds be better to avoid any python calls.

**Comment by JulienPeloton** [comment]
Hi @plaszczy,

Thanks, I agree for pure Scala user this seems baroque at first sight... This trick is mainly to avoid duplicating the information about versions. However you do not need the python call if you specify the scala version number as argument:

```
# e.g. using Scala 2.11.8
./test_scala 2.11.8
```

The python calls is only there when the script is called without explicit scala version.

**Comment by JulienPeloton** [comment]
Fixed in #120
