### ISSUE TITLE
run_part_scala.sh is failing because of assembly syntax

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/spark3D#119]
The test script `run_part_scala.sh` is failing because there is no match between the jar name produced by `sbt assembly` and the jar name used to run the job.

Action item: either change the jar name used to run the job (plus remove explicit deps as assembly jat already contains them), OR use `sbt package` (names should then match).

**Comment by plaszczy** [comment]
maybe you could use directly a scala call. version number is availbale in scala.util.Properties.versionNumberString

**Comment by JulienPeloton** [comment]
wrong issue?

**Comment by JulienPeloton** [comment]
Fixed in https://github.com/astrolabsoftware/spark3D/commit/f3b24697d03d7c08c3912f127580de7467ee29bb
