### ISSUE TITLE
Multiple class constructors in Scala: no real Java equivalent.

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/spark3D#16]
In Java, one can use different constructors to instantiate a class

```java
public class toto
  /** First constructor */
  public toto(Integer arg1) {
    // some stuff
  }

  /** Second constructor */
  public toto(String arg2) {
    // some stuff
  }
}
```

This is what is used in [GeoSpark](https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/spatialRDD/PointRDD.java) to instantiate RDD[T] for example.
As far as I know, there is no direct equivalent in Scala... So the structure will differ.

**Comment by mayurdb** [comment]
yeah, the overloading constructor has to directly call default/another overloading constructor. 

As a workaround, can we use the Object and call the appropriate constructor after having done some custom operations?

**Comment by JulienPeloton** [comment]
Solution chosen: combine object + class.
e.g. `Point3DRDD.scala`:
```scala
object Point3DRDD {
  def apply(rdd : RDD[Point3D], isSpherical: Boolean): Point3DRDD = {
    new Point3DRDD(rdd, isSpherical)
  }
}

class Point3DRDD(rdd : RDD[Point3D], override val isSpherical: Boolean) extends Shape3DRDD[Point3D] {
  def this(spark : SparkSession, filename : String, colnames : String, isSpherical: Boolean,
      format: String, options: Map[String, String] = Map("" -> "")) {
    this(CustomPoint3DRDD(spark, filename, colnames, isSpherical, format, options), isSpherical)
  }

  // Put as many different this() as you wish
}
```
